"""empty message

Revision ID: 376a7fc783f
Revises: 1d5c640215b0
Create Date: 2015-09-18 23:05:59.529284

"""

# revision identifiers, used by Alembic.
revision = '376a7fc783f'
down_revision = '1d5c640215b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trains', 'size',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trains', 'size',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
